namespace MapGen;

public sealed class GenerationConfig
{
    public int Width { get; init; } = 128;
    public int Height { get; init; } = 128;

    /// Alphanumeric seed (A-Z, a-z, 0-9), max 32 chars. Empty/null → a
    /// random 8-char seed is generated by Validate().
    public string Seed { get; set; } = "";

    public int PipelineRetryBudget { get; init; } = 5;
    public int MetaCellSize { get; init; } = 8;

    public void Validate()
    {
        if (Width < 16 || Height < 16)
            throw new System.ArgumentOutOfRangeException(
                nameof(Width), "Map dimensions must be at least 16x16.");
        if (Width % MetaCellSize != 0 || Height % MetaCellSize != 0)
            throw new System.ArgumentException(
                $"Width and Height must be multiples of MetaCellSize ({MetaCellSize}).");
        if (Seed == null) Seed = "";
        if (Seed.Length == 0) Seed = GenerateRandomSeed();
        if (Seed.Length > 32)
            throw new System.ArgumentException("Seed length must be <= 32 chars.");
        for (int i = 0; i < Seed.Length; i++)
        {
            char c = Seed[i];
            bool ok = (c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
            if (!ok) throw new System.ArgumentException(
                $"Seed contains non-alphanumeric character: '{c}'");
        }
    }

    private static string GenerateRandomSeed()
    {
        const string alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        var rng = new System.Random();
        var chars = new char[8];
        for (int i = 0; i < 8; i++) chars[i] = alpha[rng.Next(alpha.Length)];
        return new string(chars);
    }
}
